require:
  - rubocop-markdown

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - README.md
  NewCops: enable
  TargetRubyVersion: 2.7

Metrics:
  Enabled: false

Naming/FileName:
  Exclude:
    - lib/rubocop-markdown.rb
